version: '3.9'
services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    network_mode: host
    ports:
      - "8086:8086"
    volumes:
      - ./services/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf  # Configuration file
      - influxdb_data:/var/lib/influxdb2  # Persistent database storage
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=merry_acres
      - DOCKER_INFLUXDB_INIT_BUCKET=network_monitoring
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - ./services/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    restart: always

  snmp_exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp_exporter
    network_mode: host
    ports:
      - "9116:9116"
    volumes:
      - ./services/snmp_exporter/snmp.yml:/etc/snmp_exporter/snmp.yml
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: host
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    links:
      - snmp_exporter
    restart: always